# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 17:03
from __future__ import unicode_literals

import aldryn_apphooks_config.fields
import app_data.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stupid_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('namespace', models.CharField(default=None, max_length=100, unique=True, verbose_name='instance namespace')),
                ('app_data', app_data.fields.AppDataField(default='{}', editable=False)),
            ],
            options={
                'verbose_name': 'blog config',
                'verbose_name_plural': 'blog configs',
            },
        ),
        migrations.CreateModel(
            name='BlogConfigTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('app_title', models.CharField(max_length=234, verbose_name='application title')),
                ('object_name', models.CharField(default='article', max_length=234, verbose_name='object name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='stupid_blog.BlogConfig')),
            ],
            options={
                'managed': True,
                'db_table': 'stupid_blog_blogconfig_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'blog config Translation',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='app_config',
            field=aldryn_apphooks_config.fields.AppHookConfigField(help_text='When selecting a value, the form is reloaded to get the updated default', null=True, on_delete=django.db.models.deletion.CASCADE, to='stupid_blog.BlogConfig', verbose_name='app. config'),
        ),
        migrations.AlterUniqueTogether(
            name='blogconfigtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
