# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 12:30
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('stupid_blog', '0002_auto_20160225_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='content', to='cms.Placeholder'),
        ),
    ]
