# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 12:53
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('stupid_blog', '0003_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image', verbose_name='cover image'),
        ),
    ]
